version: "3.7"
services:
  account-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kidsloop
      - POSTGRES_DB=account_service
      - NEW_RELIC_LICENSE_KEY=eu01xx806da43b4e6328a73e58f550acFFFFNRAL
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_PASSWORD=kidsloop
      - POSTGRES_DB=account_service
    ports:
      - '5432:5432'
    volumes: 
      - ./database/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5