definitions:
  model.APIError:
    properties:
      code:
        type: string
      details: {}
      message:
        type: string
    type: object
  model.Account:
    properties:
      id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: accounts-service documentation
  version: 1.0.0
paths:
  /accounts:
    put:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIError'
      summary: Create a new account
  /accounts/{accountId}:
    delete:
      parameters:
      - description: Account ID
        in: query
        name: accountId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIError'
      summary: Delete an account
    get:
      parameters:
      - description: Account ID
        in: path
        name: accountId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIError'
      summary: Get details of account
swagger: "2.0"
